objects/Crew_Member__c/Crew_Member__c.object-meta.xml
<CustomObject>
    <label>Crew Member</label>
    <nameField>
        <label>Crew Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Crew Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Crew_Member__c/fields/Flight__c.field-meta.xml
<CustomField>
    <fullName>Flight__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flight</label>
    <referenceTo>Flights__c</referenceTo>
    <relationshipLabel>Crew Members</relationshipLabel>
    <relationshipName>Crew_Members</relationshipName>
    <type>Lookup</type>
</CustomField>

objects/Flights__c/fields/From__c.field-meta.xml
<CustomField>
    <fullName>From__c</fullName>
    <label>From</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

objects/Flights__c/fields/Reaching_Time__c.field-meta.xml
<CustomField>
    <fullName>Reaching_Time__c</fullName>
    <label>Reaching Time</label>
    <type>DateTime</type>
</CustomField>

objects/Flights__c/fields/Starting_Time__c.field-meta.xml
<CustomField>
    <fullName>Starting_Time__c</fullName>
    <label>Starting Time</label>
    <type>DateTime</type>
</CustomField>

classes/FlightSearch.cls
/**
 * @description       : customSearchSobjectLWC
**/
public with sharing class FlightSearch {
    @AuraEnabled(cacheable=true)
    public static list<Flights__c> getFlightList(string flightName) {
        list<Flights__c> flightListRecord = new list<Flights__c>();
        String tempName;
        if(String.isNotBlank(flightName)){
            tempName = String.escapeSingleQuotes(flightName.trim()) + '%';
        }
        for(Flights__c finObj : [Select Name,From__c,To__c,Starting_Time__c,Reaching_Time__c
                            From Flights__c
                            WHERE Name LIKE : tempName]){
           flightListRecord.add(finObj);
        }
        
         if(flightListRecord.size() == 0){
            throw new AuraHandledException('No Flights Found..'); 
         }
         
        return flightListRecord;
    }
    @AuraEnabled(cacheable=true)
    public static list<Crew_Member__c> getCrewList(string crewName,String flightName) {
        list<Crew_Member__c> crewListRecord = new list<Crew_Member__c>();
        String tempName;
        if(String.isNotBlank(crewName)){
            tempName = String.escapeSingleQuotes(crewName.trim()) + '%';
        }
        for(Crew_Member__c crewObj : [Select Name
                            From Crew_Member__c
                            WHERE Name LIKE : tempName and Flight__r.Name=:flightName]){
                                crewListRecord.add(crewObj);
        }
        
         if(crewListRecord.size() == 0){
            throw new AuraHandledException('No Crew Found..'); 
         }
         
        return crewListRecord;
    }
    @AuraEnabled(cacheable=true)
    public static List<SObject> gettingrecordId(string SObj,string Name) {
        if(SObj=='Crew_Member__c'){
        return [Select Id,Name,Age__c,Role__c,Flight__r.Name,Email__c from Crew_Member__c where Name=:Name Limit 1];
        }else{
            return [Select Id,Name,From__c,To__c,Starting_Time__c,Reaching_Time__c from Flights__c where Name=:Name Limit 1];   
        }
    }
    @AuraEnabled(cacheable=true)
    public static void bookFlight(){

    }
}